# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
java_version=25
lombok_version=9.4.0
# Mod properties
mod_version=0.6.1
maven_group=cc.gahaha
archives_name=EntityCount
mod_id=entitycount
# Minecraft properties
minecraft_version=26.2
minecraft_version_range_fabric=>=26.2 <26.3
minecraft_version_range_neoforge=[26.2,26.3)
# Dependencies
fabric_loader_version=0.19.3
fabric_loom_version=1.17-SNAPSHOT
fabric_api_version=0.153.0+26.2
neoforge_version=26.2.0.7-beta
neoforge_version_range=[26.2,26.23
modmenu_version=20.0.0-beta.4
cloth_config=26.2.155
shadow_version=9.2.2
moddevgradle_version=2.0.141