pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = "Terraformers"
            url = "https://maven.terraformersmc.com/"
        }
        maven { url "https://maven.shedaniel.me/" }
    }
}

rootProject.name = 'EntityCount'

include 'common'
include 'fabric'
include 'neoforge'