apply plugin: 'multiloader-common'
apply plugin: 'net.fabricmc.fabric-loom'

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"

    compileOnly("me.shedaniel.cloth:cloth-config:${rootProject.cloth_config}") {
        exclude(group: "net.fabricmc.fabric-api")
        exclude(group: "net.fabricmc:fabric-loader")
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}